inventoryManagement/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from main.views import UserAutocomplete , ProjectAutocomplete
from main.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^table/', include('table.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^', include('main.urls')),
    url(
        r'^user-autocomplete/$',
        UserAutocomplete.as_view(),
        name='user-autocomplete',
    ),
    url(
        r'^project-autocomplete/$',
        ProjectAutocomplete.as_view(),
        name='project-autocomplete',
    ),
    url(
        r'^equipment-autocomplete/$',
        EquipmentAutocomplete.as_view(),
        name='equipment-autocomplete',
    ),
    url(r'^addproject/$', add_project, name='addproject'),
    url(r'^table/data/$', MyDataView.as_view(), name='table_data'),
    url(r'^table/admdata/$', MyAdmDataView.as_view(), name='admtable_data'),
    url(r'^table/issuedata/$', MyIssueView.as_view(), name='issuetable_data'),
    url(r'^table/admissuedata/$', MyAdmIssueView.as_view(), name='admissuetable_data'),
    url(r'^table/myfollowdata/$', MyFollowView.as_view(), name='myfollowtable_data'),
    
]

main/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from main.views import *

app_name = 'main'
urlpatterns = [
    # ex: /polls
    url(r'^$', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^index/$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<id>[0-9]+)/$', views.instance_search, name='instancesearch'),
    url(r'^addproject/$', views.add_project, name='addproject'),
    url(r'^profile/(?P<id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^editprofile/$', views.update_profile, name='editprofile'),
    url(r'^follow/$', views.follow, name='follow'),
    url(r'^issue/(?P<issue_id>[0-9]+)/$', views.issue, name='issue'),
    url(r'^return/$', views.return_equipment, name='return'),
    url(r'^cancelfollow/$', views.cancel_follow, name='cancelfollow'),
    url(r'^issueances/(?P<id>[0-9]+)/$', views.issues, name='issueance'),
    url(r'^issueances/$', views.all_issues, name='allissueance'),
    url(r'^admprofile/$', views.admprofile, name='admprofile'),
    
]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from dal import autocomplete
from django.urls import reverse


from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe
from django.forms import widgets
from django.conf import settings

class RelatedFieldWidgetCanAdd(widgets.Select):

    def __init__(self, related_model, related_url=None, *args, **kw):

        super(RelatedFieldWidgetCanAdd, self).__init__(*args, **kw)

        if not related_url:
            rel_to = related_model
            info = (rel_to._meta.app_label, rel_to._meta.object_name.lower())
            related_url = 'admin:%s_%s_add' % info

        # Be careful that here "reverse" is not allowed
        self.related_url = related_url

    def render(self, name, value, *args, **kwargs):
        self.related_url = reverse(self.related_url)
        output = [super(RelatedFieldWidgetCanAdd, self).render(name, value, *args, **kwargs)]
        output.append('<a href="%s" target="_blank" class="add-another" id="add_id_%s" onclick="return showAddAnotherPopup(this);"> ' % \
            (self.related_url, name))
        output.append('<img src="%sadmin/img/icon-addlink.svg" width="10" height="10" alt="%s"/></a>' % (settings.STATIC_URL, 'Add Another'))
        return mark_safe(''.join(output))








class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    first_name = forms.CharField(required=True, label="First Name")
    last_name = forms.CharField(required=True, label="Last Name") 

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')
    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email already used")
        return data  


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name','members')
        widgets = {'members': autocomplete.ModelSelect2Multiple(url='user-autocomplete', attrs={'data-html': True})}


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']



class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['branch', 'enrollment_no', 'year'] 

class IssueanceForm(forms.ModelForm):   
    project = forms.ModelChoiceField(
       required=False,
       queryset=Project.objects.all(),
       widget=RelatedFieldWidgetCanAdd(Project, related_url="addproject")
                                )
    class Meta:
        model = Issueance
        fields = ['issued_by', 'project', 'year'] 
        widgets = {'project': autocomplete.ModelSelect2(url='project-autocomplete', attrs={'data-html': True}),
                    'issued_by' :autocomplete.ModelSelect2(url='user-autocomplete') }                        
          

class PostForm(forms.Form):
    project = forms.ModelChoiceField(
        label='Project',
        required=True,
       queryset=Project.objects.all(),
       widget=RelatedFieldWidgetCanAdd(Project, related_url="addproject"))
    time = forms.IntegerField(label='Time(days)')   
    equipments = forms.ModelMultipleChoiceField( label='Equipments',
        required=True,
        queryset=EquipmentInstance.objects.filter(is_available=True),
        widget=autocomplete.ModelSelect2Multiple(url='equipment-autocomplete', attrs={'data-html': True}),
    )

    def __init__(self, user, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['project'].queryset = user.project_set.all()
    

main/views.py
# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .forms import *
from .tables import *
from .models import *
import datetime
from notify.signals import notify
from dal import autocomplete
from django.db.models import Q
from django.utils import timezone
try:
    from django.utils import simplejson as json
except ImportError:
    import json

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('main/acc_active_email.html', {
                'user':user, 
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = 'Activate your Inventory management account.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    
    else:
        form = SignupForm()
    
    return render(request, 'main/signup.html', {'form': form})



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required(login_url='/')
def index(request):
    if UserProfile.objects.get(user=request.user).is_admin == True:
        return render(request, 'main/index_admin.html')
    issuetable = MyIssueanceTable()
    followtable = MyFollowTable()
    return render(request, 'main/index.html', {'issuetable': issuetable, 'followtable': followtable})        

@login_required(login_url='/')
def search(request):
    """for searching different items available depending on get request,
    display all items available for no filters """ 
    equipments = Equipment.objects.all()
    if UserProfile.objects.get(user=request.user).is_admin == True:
        equipment = EquipmentAdmTable() 
    else:
        equipment = EquipmentTable()      
    return render(request, "main/search.html", {'equipment': equipment, 'equipments': equipments})


@login_required(login_url='/')
def instance_search(request, id):
    """for searching different items available depending on get request,
    display all items available for no filters """ 
    equipment=get_object_or_404(Equipment, pk=id)
    qs = equipment.eqins.filter(decommisioned=False)
    if UserProfile.objects.get(user=request.user).is_admin == True:
        equipmenttable = EquipmentInstanceTable(qs) 
    else:
        equipmenttable = EquipmentInstanceTable(qs)      
    return render(request, "main/searchinstance.html", {'equipment': equipment, 'equipmenttable': equipmenttable})    


@login_required(login_url='/')
def issues(request, id):
    equipment=get_object_or_404(Equipment, pk=id)
    qs = Issueance.objects.filter(equipmentInstance__equipment=equipment)
    issuetable = IssueanceTable(qs)
    if UserProfile.objects.get(user=request.user).is_admin == True:
        issuetable = IssueanceAdmTable(qs)
    return render(request, "main/issues.html", {'issuetable': issuetable})

def all_issues(request):
    equipments=Equipment.objects.all()
    qs = []
    for equipment in equipments :
        if equipment.eqins.filter(is_available=False, decommisioned=False).count() != 0:
            qs.append(equipment)
    issuetable = EquipmentIssueTable(qs)
    if UserProfile.objects.get(user=request.user).is_admin == True:
        issuetable = EquipmentIssueTable(qs)
    return render(request, "main/issues.html", {'issuetable': issuetable})    


@login_required(login_url='/')
def profile(request, id):
    user  = get_object_or_404(User, pk=id)
    userprofile = get_object_or_404(UserProfile, user=user)
    return render(request, "main/profile.html", {'userp': user, 'userprofile': userprofile})


@login_required(login_url='/')
def admprofile(request):
    if UserProfile.objects.get(user=request.user).is_admin == False:
        return HttpResponse('You cannot access this page')       
    userprofile  = get_object_or_404(UserProfile, enrollment_no=request.GET.get('enrollment_no'))
    user = userprofile.user
    qs = Issueance.objects.filter(issued_by=user, returned=False) 
    issuetable = IssueanceAdmTable(qs)
    form = PostForm(user)
    return render(request, "main/profile_adm.html", {'userp': user, 'userprofile': userprofile, 'issuetable':issuetable, 'form':form })    


@login_required(login_url='/')
def update_profile(request):
    """update the userprofile"""
    if request.method == 'POST':
        user = request.user
        profile = UserProfile.objects.get(user=user)
        userform = UserForm(request.POST, instance=user)
        profileform = UserProfileForm(request.POST, instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            f = profileform.save(commit=False)
            f.user = request.user
            f.save()
            context = {
            'userform'  : userform,
            'profileform': profileform
            }   
            return HttpResponseRedirect(reverse('main:search'), context)
        else :
            context = {
            'userform'  : userform,
            'profileform': profileform
            } 
            return HttpResponseRedirect(reverse('main:search'), context)
    else:    
        profile = UserProfile.objects.get(user = request.user)
        userform = UserForm(instance=request.user)
        profileform = UserProfileForm(instance=profile)
        context = {
            'userform'  : userform,
            'profileform': profileform
        }
        return render(request, 'main/editProfile.html', context)


@login_required(login_url='/')
def issue(request, issue_id):
    if UserProfile.objects.get(user=request.user).is_admin == False:
        return HttpResponse('You dont have required permissions to issue the equipment') 
    user = get_object_or_404(User, pk=issue_id)
    form = PostForm(user)
    if request.method == "POST":
        if UserProfile.objects.get(user=request.user).is_admin == True:
            user = get_object_or_404(User, pk=issue_id)
            form = PostForm(user, request.POST)
            if form.is_valid():
                user = get_object_or_404(User, pk=issue_id)
                time = form.cleaned_data['time']
                project = form.cleaned_data['project']
                for equipment in form.cleaned_data['equipments']:
                    if  equipment.is_available:
                        Issueance.objects.create(issued_by=user, project=project, equipmentInstance=equipment, year=time,
                        enrollment_no = user.userprofile.enrollment_no )
                        equipment.is_available=False
                        equipment.save()
                response = redirect('main:admprofile')
                response['Location'] += '?enrollment_no=%d' % user.userprofile.enrollment_no
                return response    

        else:
            return HttpResponse('You dont have required permissions to issue the equipment') 
    return render(request, 'main/issue.html', {'form': form})
        

@login_required(login_url='/')
def return_equipment(request):
    if request.method == "POST" :
        Issueance_pk = request.POST.get('Issueance_pk')
        if UserProfile.objects.get(user=request.user).is_admin == True:
            issue = Issueance.objects.get(pk = Issueance_pk)
            equipment = issue.equipmentInstance
            issue.returned = True
            issue.save()
            issue.return_date = timezone.now()
            equipment.is_available=True
            issue.save()
            equipment.save()
            followers = list(equipment.equipment.followers.all())
            notify.send(request.user, recipient_list=followers, actor=equipment,
                        verb='is available now!.',)
            notification = "equipment returned"
            ctx = { 'noti' : True,}
            return HttpResponse(json.dumps(ctx), content_type='application/json')
    ctx = { 'noti' : False,}
    return HttpResponse(json.dumps(ctx), content_type='application/json')            


@login_required(login_url='/')
def follow(request):
    """ generate a issue request for items unavailable """
    if request.method == "POST":
        equip = request.POST.get('id')
        equipment = get_object_or_404(Equipment, pk=equip)
        try:
            follow = Follow(equipment = equipment, user = request.user, is_active=True)
            follow.save()
            ctx = { 'noti' : True,}
            return HttpResponse(json.dumps(ctx), content_type='application/json')
        except IntegrityError:

main/templates/main/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}
{% endautoescape %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  
  <title>Inventory Management System</title>
</head>
<body>
  <center>
        <a href="{% url 'main:search' %}"><h5>Home</h5></a>
        <a href="{% url 'main:profile' request.user.id %}"><h5>My Profile</h5></a>
        <a href="{% url 'main:editprofile' %}"><h5>Edit Profile</h5></a>
        <a href="{% url 'main:issueances' 2 %}"><h5>Issued Equipments</h5></a>
        <a href="{% url 'main:logout' %}"><h5>Logout</h5></a>
      </center>
  <div class="container">
    <br>
    {% block content %}{% endblock content %}
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% block script %}{% endblock script %}
</body>
</html> 

main/templates/main/index1.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    {% load table_tags %}
    {% load notification_tags %}
    {% include_notify_js_variables %}
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Issued Equipments</title>
    <link href="{% static 'table/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'table/js/jquery.min.js' %}"></script>
    <script src="{% static 'table/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'notify/notifyX.min.js' %}"></script>
</head>
<body>
  <center>
        <a href="{% url 'main:search' %}"><h5>View Inventory</h5></a>
        <a href="{% url 'main:editprofile' %}"><h5>Edit Profile</h5></a>

        <a href="{% url 'main:allissueance'  %}"><h5>Issued Equipments</h5></a>
        <a href="{% url 'main:logout' %}"><h5>Logout</h5></a>
    
    <br><br>
    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Notifications
  <span class="caret"></span></button>
  <ul class=" notification-box-list dropdown-menu">
    {% user_notifications %}
</ul>
    </div>
    </center>
    <div class="container" style="margin-top: 10px">
    	<h3>My profile</h3>
    		<center>
    <h6>{{ reuqest.user.username }}</h6>
    <h6>{{ request.user.first_name }} {{ request.user.last_name }}</h6>
    <h6> {{ request.user.email }}</h6>
    <br><br>
    <ul>
    	{% if request.user.userprofile.enrollment_no %}<li>Enrollment No.: {{ request.user.userprofile.enrollment_no }}</li>{% endif %}
    	{% if request.user.userprofile.branch %}<li> Branch : {{ request.user.userprofile.branch }}</li>{% endif %}
    	{% if request.user.userprofile.year %}<li>Year : {{ request.user.userprofile.year }} </li>{% endif %}
    </ul>
    <br>
</center>

        <h3>My Issued Equipments</h3>
        <br />
        {% render_table issuetable %}
        <br><br><br>
        <h3>Recently Following</h3>
        <br />
        {% render_table followtable %}


       
    </div>
    


    <script>


function cancelfollow(name){
        console.log(name);
      $.ajax({
               type: "POST",
               url: "{% url 'main:cancelfollow' %}",
               data: {'request_pk': name, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: "json",
               success: function(response) {
                   location.reload();
                },
                error: function(rs, e) {
                       alert(rs.responseText);
                }
          }); 
    }
</script>
</body>
</html>

main/templates/main/issue.html
{% extends 'main/base.html' %}

{% load static %}
{% block content %}
    <form method="post" action=".">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="">
</form>




<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
<script type="text/javascript" src="/admin/jsi18n/"></script>

<script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>


<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/SelectBox.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/SelectFilter2.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}" />

{{ form.media }}
{% endblock %}

main/templates/main/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load table_tags %}
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Dashboard</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="{% static 'table/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'table/js/jquery.min.js' %}"></script>
    <script src="{% static 'table/js/bootstrap.min.js' %}"></script>


<style type="text/css">
  .card{
    border:1px solid rgba(0,0,0,.125);
  }
</style>
<style type="text/css">
    .navbar .navbar-toggler{
    border:1px solid transparent;
    background-color: transparent;
    padding-top: 13px;
  }
</style>
    <script type="text/javascript">
 function hello() {
        
 {% for equipment in equipments %}
                {% if request.user in equipment.followers.all %}
                    $('#'+{{ equipment.id }}+'-user').html( '<input type="button"  name="'+{{equipment.id }}+'" value="Unfollow" onclick="cancelfollow(this.name)" />' );
                    console.log({{ equipment.id }});
                
                {% else %}
                      $('#'+{{ equipment.id }}+'-user').html( '<input type="button"  name="'+{{equipment.id }}+'" value="Follow" onclick="follow(this.name)" />' );
                {% endif %}
{% endfor %} 

};
</script>

    <script src="{% static 'notify/notifyX.min.js' %}"></script>
    <link href="{% static 'table/css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'table/css/demo.css' %}" rel="stylesheet" />

</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-color="orange" data-image="https://images.unsplash.com/4/madebyvadim.jpg?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=78688b2cbb91cc81bba44ed9f5b4dc9f&auto=format&fit=crop&w=1498&q=80">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="#asdf" class="simple-text">
                        Inventory Management
                    </a>
                </div>
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:index' %}">
                            <i class="nc-icon nc-chart-pie-35"></i>
                            <p>Home</p>
                        </a>
                    </li>
                    {% if not request.user.userprofile.is_admin %}
                    <li>
                        <a class="nav-link" href="{% url 'main:editprofile' %}">
                            <i class="nc-icon nc-circle-09"></i>
                            <p>User Profile</p>
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a class="nav-link active" href="{% url 'main:search' %}">
                            <i class="nc-icon nc-notes"></i>
                            <p>View Inventory</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'main:allissueance'  %}">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Issued Equipments</p>
                        </a>
                    </li>
                    <!-- <li>
                        <a class="nav-link" href="./icons.html">
                            <i class="nc-icon nc-atom"></i>
                            <p>Icons</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="./maps.html">
                            <i class="nc-icon nc-pin-3"></i>
                            <p>Maps</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="./notifications.html">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>Notifications</p>
                        </a>
                    </li>
                    <li class="nav-item active active-pro">
                        <a class="nav-link active" href="upgrade.html">
                            <i class="nc-icon nc-alien-33"></i>
                            <p>Upgrade to PRO</p>
                        </a>
                    </li> -->
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                   
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url 'main:logout'%}">
                                Log out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
            <!-- End Navbar -->
            
<div class="content">
                <div class="container-fluid">
                    <div class="row">
                      <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                </div>
                                <div class="card-body">{% render_table equipment %}
                        </div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</body>
<!--   Core JS Files   -->

<script src="{% static 'table/js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'table/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'table/js/plugins/bootstrap-switch.js' %}"></script><!--  Chartist Plugin  -->
<script src="{% static 'table/js/plugins/chartist.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'table/js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="{% static 'table/js/light-bootstrap-dashboard.js' %}" type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'table/js/demo.js' %}"></script>
<script type="text/javascript">
    function cancelfollow(name){
        console.log(name);
      $.ajax({
               type: "POST",
               url: "{% url 'main:cancelfollow' %}",
               data: {'request_pk': name, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: "json",
               success: function(response) {
                   location.reload();
                },
                error: function(rs, e) {
                       alert(rs.responseText);
                }
          }); 
    }

function follow(name){
        console.log(name);
      $.ajax({
               type: "POST",
               url: "{% url 'main:follow' %}",
               data: {'id': name, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: "json",
               success: function(response) {
                   location.reload();
                },
                error: function(rs, e) {
                       alert(rs.responseText);
                }
          }); 
    }        
</script>

</html>